/**
 * Taken from http://www.codejava.net/coding/how-to-calculate-md5-and-sha-hash-values-in-java
 */

/**
 * Do not edit this file
 */

package utility;

import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;


public class HashGenerator {
	
	public static String generateHash(String data) throws NoSuchAlgorithmException, UnsupportedEncodingException {
		return hashString(data, "SHA-256");
	}
	
	private static String hashString(String data, String algorithm) throws NoSuchAlgorithmException, UnsupportedEncodingException {
		MessageDigest digest = MessageDigest.getInstance(algorithm);
		byte[] hashedBytes = digest.digest(data.getBytes("UTF-8"));
		return byteArrayToString(hashedBytes);
	}

	private static String byteArrayToString(byte[] arrayBytes) {
		StringBuffer stringBuffer = new StringBuffer();
		for (int i = 0; i < arrayBytes.length; i++) {
			stringBuffer.append(Integer.toString((arrayBytes[i] & 0xff) + 0x100, 16)
					.substring(1));
		}
		return stringBuffer.toString();
	}
	
}